### ISSUE TITLE
Taking too much time 

### ISSUE THREAD

**Issue by vedprakash2017** [hldh214/buff2steam#10]
As you are using python and just sending 2 request and still it's taking too much time. If I used js then we can get a better speed ? Is it possible to get inspect link of listed item on steam market to get float values?

**Comment by hldh214** [comment]
In my opinion, the performance is only related to 3rd party api(buff, steam, ...) response time.
And no matter whatever programming language we choose we can't optimize that a lot.

But feel free to contribute any thought/code you are interested at.

**Comment by vedprakash2017** [comment]
And what about inspect link is there any api for it? To get float values.

**Comment by hldh214** [comment]
> And what about inspect link is there any api for it? To get float values.

I'm sorry but I don't know.
Maybe you can discribe a little more about it with some links or screenshots.

**Comment by vedprakash2017** [comment]
![inspect](https://user-images.githubusercontent.com/33026804/111038084-2ac78880-844d-11eb-9b2f-7e398ba0bf1e.png)

you can get inspect link by clicking on the icon and for float here I am using one csgo float extension.

**Comment by vedprakash2017** [comment]
Man, I got banned from the buff. have you not added timeout between requests.

**Comment by hldh214** [comment]
Oh I get it :P

Since the inspect link and float value are CSGO-only features, and buff2steam is almost a "game-unrelated" project.
Which means we can trade with not only csgo skins but also dota2 skins if you like.
Plus, this project is meant to do some "high throw bargain - hunting" things so I think maybe those aren't helpful to this project.

> Man, I got banned from the buff. have you not added timeout between requests.

OOPS, sorry to hear that, I never thought buff would actually ban someone even there are so many bots there.
Could you please describe more about your situation, so I can do a summarize and update the README file.
