### ISSUE TITLE
Too many request : Web

### ISSUE THREAD

**Issue by imanewbiecomer** [hldh214/buff2steam#25]
![image](https://github.com/hldh214/buff2steam/assets/148615774/627c9b32-e115-4115-a367-209199f2e58a)

**Comment by imanewbiecomer** [comment]
![image](https://github.com/hldh214/buff2steam/assets/148615774/a7da26cf-7625-4d48-944f-d6ffe55e561a)
Can u fix this problem ?

**Comment by hldh214** [comment]
According to this comment https://github.com/hldh214/buff2steam/issues/20#issuecomment-1692883155

We will make every effort to obtain more data from Steam, However, please note that there may be instances where our requests are blocked by Steam, so I set this log level to `DEBUG`.

So you can simply turn off debug mode and enjoy
https://github.com/hldh214/buff2steam/blob/e4ec16523934dec76173cbd003b7d052f1c52dff/config.sample.json#L2-L3

**Comment by imanewbiecomer** [comment]
Im very glad to see ur repond. But i have one more problem. In buff2steam log. i can not see the b_o_ratio? Since i updated the code, i have not see it again :< Whats wrong with it dude?

**Comment by hldh214** [comment]
If you read this issue (https://github.com/hldh214/buff2steam/issues/20#issuecomment-1692883155), you'll see that the Steam API, which provides the `b_o_ratio`, has a much stricter rate limit. Therefore, we made changes to the script to only display the `b_o_ratio` if it is available. You can restart the script and check if the first approximately 10 results have the `b_o_ratio` field. This is because you haven't reached the rate limit yet.
