### ISSUE TITLE
Auto-cancel

### ISSUE THREAD

**Issue by frendri** [hldh214/buff2steam#9]
Hello. You know how i can cancels orders when i can ask item only from BUFF APP(not the seller send me)? I tried this
`cancel_data = {
    "bill_order_id": i['id'],
    "game": "csgo"
}
cancel_order = s.post("https://buff.163.com/api/market/bill_order/deliver/cancel", json=cancel_data, headers={"Referer":"https://buff.163.com/market/buy_order/history?game=csgo&state=trading","X-CSRFToken": s.cookies.get_dict()['csrf_token']})`
But response is:
`{'code': 'BillOrder Invalid', 'error': 'The order is abnormal, please contact support', 'extra': None}`
But i know that is possible
this code also work in ussually cancel order

**Comment by hldh214** [comment]
I am not sure what you mean. (ask item only from BUFF APP?)
Could you please take some screenshots of this action and make a description?

**Comment by danil995566** [comment]
I wrote my bot that auto buy skins and chooses Send offer by seller, and also automatically accepts exchanges on Steam.
![image](https://user-images.githubusercontent.com/36545681/90655581-ce074500-e252-11ea-92c5-d2e8426019f8.png)
But the problem is that sometimes, when buying, it is impossible for the seller to send me an offer. 
![image](https://user-images.githubusercontent.com/36545681/90655378-8c769a00-e252-11ea-89db-6360cef35f96.png)
And if you do not create an exchange 3 times through the BUFF application, then a purchase ban arrives. There is no button on the site to cancel such an order. But my friend said that his bot can cancel such orders through a request, but my request is not core

**Comment by hldh214** [comment]
Well, i got your point.
But currently i dont have time to reproduce this and make further investigation.
So maybe asking your "friend" is the quickly way to achieve this.

Sorry for not helping you.

**Comment by danil995566** [comment]
How do you automate trading in the presence of such an error?

**Comment by hldh214** [comment]
Actually, "auto trading" things are not been developed since last year, you can take a look at the history:
https://github.com/hldh214/buff2steam/commits/master/buff2steam/buff.py

And in the early 2019, buff only has one trade method, which is using bot account to be the middle between buyer and seller, seller send the skin to the bot, bot send it to the buyer.
So at that time we dont meet that situation.
